INSERT INTO USERS
VALUES ('rishi2616', 'Iofdtiger#16', true);

INSERT INTO USERS
VALUES ('rishi1626', 'Iofdtiger@16', true);

INSERT INTO AUTHORITIES
VALUES ('rishi2616', 'ROLE_USER');

INSERT INTO AUTHORITIES
VALUES ('rishi1626', 'ROLE_ADMIN');